### ISSUE TITLE
Can´t open V2_Connector_90deg_tube10mm.stl

### ISSUE THREAD

**Issue by Pull3D** [schemen/OpenFormicaria#1]
Hi, I can´t open V2_Connector_90deg_tube10mm.stl

**Comment by schemen** [comment]
heyo!

I have fixed it with https://github.com/schemen/OpenFormicaria/commit/597b1aac63ff105e4bd7caaf252c8e0b19a316a0

Let me know if things work for you! You can download it here: https://github.com/schemen/OpenFormicaria/blob/master/Connectors/STL/Connector%20Version%202/V2_Connector_90deg_tube10mm.stl
