### ISSUE TITLE
Which tube connector for test tube?

### ISSUE THREAD

**Issue by BjornB2** [schemen/OpenFormicaria#7]
Hi! 

Thanks for your design. I am currently printing a new home for my ants :)

In the documentation it says the test tube goes over the tube connector, but what are the outer diameters of the 3 tube connectors? Only the inner diameters are specified (although it's called circumference which is incorrect I think).

Thanks
Björn

**Comment by schemen** [comment]
Hi!

I then think it's a wrong wording. The circumference is the outside of the tube connectors.

I think I should also change the wording there. It's meant to be the outer circumference of course! (Inner would not really help you at all :) )

**Comment by BjornB2** [comment]
Ah that clears it up. But I also need to attach tubes from my old nest and those are 10mm outside diameter. Cant put them over a tube connector since the hole would be to small for the bigger ants i am afraid. I'll check the cad files tomorrow.

**Comment by schemen** [comment]
Ah gotcha, whats the inside diameter? 8mm? That should be fairly easy to modify in CAD

**Comment by BjornB2** [comment]
Inside diameter would be to small to put it over a tube connector. The final hole would be to small for the bigger ants. I have harvester ants and they have some really large ants.  It would be better to stick the hose in the connector so to make the hole in the connector 10mm.

**Comment by schemen** [comment]
Gotcha, feel free to add a connector like that. Otherwise, if you give me the exact specs I can cook something up in the following days.

**Comment by BjornB2** [comment]
I just found out that the 14mm tube connector has a 10mm hole, so I can use that one for my 10mm connection hose :)
